import type { Metadata, Viewport } from 'next'
import { Press_Start_2P, VT323 } from 'next/font/google'
import './globals.css'
import { SkipLink } from '@/components/SkipLink'
import { LanguageProvider } from '@/i18n/LanguageProvider'
import { en, es } from '@/i18n'
import { links, person, siteUrl } from '@/data/site'

/**
 * Two bitmap faces, both single-weight, both loaded with `latin-ext` because
 * the Spanish copy is full of accents and inverted punctuation — a face without
 * that subset would drop every "ñ", "é" and "¿" to a fallback and break the
 * pixel grid mid-word.
 */
const pressStart = Press_Start_2P({
  subsets: ['latin', 'latin-ext'],
  weight: '400',
  variable: '--font-press-start',
  display: 'swap',
})

const vt323 = VT323({
  subsets: ['latin', 'latin-ext'],
  weight: '400',
  variable: '--font-vt323',
  display: 'swap',
})

/**
 * Metadata is authored in Spanish — the language the page renders in on a cold
 * load — with the English description carried alongside it, and both locales
 * declared to Open Graph. `metadataBase` comes from an env var so a custom
 * domain can be added later without inventing one now.
 */
export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    default: es.meta.title,
    template: `%s — ${person.name}`,
  },
  description: es.meta.description,
  applicationName: person.name,
  authors: [{ name: person.name, url: links.github }],
  creator: person.name,
  keywords: [
    'Andrés Felipe Zúñiga Zuluaga',
    'Full Stack Developer',
    'Ingeniero de Sistemas y Computación',
    'Systems and Computer Engineer',
    'React',
    'Next.js',
    'Electron',
    'Universidad del Quindío',
  ],
  alternates: {
    canonical: '/',
  },
  /**
   * The favicon is a static file in `public/`, so it is not picked up by the
   * `icon.tsx` convention. The social card is generated by a route handler under
   * a `.png` URL rather than by the `opengraph-image.tsx` convention, because
   * GitHub Pages types a response from the file extension alone. Both are
   * therefore declared here.
   */
  icons: {
    icon: [{ url: '/logo.ico', type: 'image/x-icon', sizes: '16x16 32x32 48x48 64x64' }],
  },
  openGraph: {
    type: 'profile',
    url: '/',
    siteName: person.name,
    title: es.meta.title,
    description: es.meta.description,
    locale: es.meta.localeTag.replace('-', '_'),
    alternateLocale: [en.meta.localeTag.replace('-', '_')],
    images: [
      { url: '/opengraph-image.png', width: 1200, height: 630, alt: es.meta.ogAlt },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: en.meta.title,
    description: en.meta.description,
    images: ['/opengraph-image.png'],
  },
  robots: {
    index: true,
    follow: true,
  },
}

export const viewport: Viewport = {
  themeColor: '#1a1a2e',
  colorScheme: 'dark',
}

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html
      // Spanish is the default; `LanguageProvider` updates this attribute when
      // the visitor switches.
      lang={es.meta.locale}
      data-scroll-behavior="smooth"
      className={`${pressStart.variable} ${vt323.variable} h-full`}
    >
      <body className="flex min-h-full flex-col bg-bg text-ink">
        <LanguageProvider>
          <SkipLink />
          {children}
        </LanguageProvider>
      </body>
    </html>
  )
}
